#Hugo configuration
title = "Some"
baseURL = "https:\/\/other.some.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
cookiedomain = ""
